NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.reg.track.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.reg.track.com-cert.pem
    OrganizationalUnitIdentifier: peer
